name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation:
  path:
  flutter_screenutil: ^5.9.1
  freezed_annotation: ^2.4.1
  objectbox: ^4.0.0
  objectbox_flutter_libs: ^4.0.0
  path_provider_linux: ^2.2.0
  path_provider: ^2.1.3
  path_to_regexp: ^0.4.0
  table_calendar: ^3.0.9
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  snackbar: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.10
  objectbox_generator: any
  riverpod_generator: ^2.4.0


flutter:
  uses-material-design: true
